CREATE TABLE IF NOT EXISTS `friendship` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `owner` BIGINT UNSIGNED NOT NULL ,
  `target` BIGINT UNSIGNED NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC);